/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Todo } from "./components/app-todo-form/app-todo-form";
import { Todo as Todo1 } from "./components/app-todo-form/app-todo-form";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppTodoForm {
    }
    interface AppTodoList {
        "todos": Todo[];
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTodoFormElement extends Components.AppTodoForm, HTMLStencilElement {
    }
    var HTMLAppTodoFormElement: {
        prototype: HTMLAppTodoFormElement;
        new (): HTMLAppTodoFormElement;
    };
    interface HTMLAppTodoListElement extends Components.AppTodoList, HTMLStencilElement {
    }
    var HTMLAppTodoListElement: {
        prototype: HTMLAppTodoListElement;
        new (): HTMLAppTodoListElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "app-todo-form": HTMLAppTodoFormElement;
        "app-todo-list": HTMLAppTodoListElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppTodoForm {
        "onCreate"?: (event: CustomEvent<Todo>) => void;
    }
    interface AppTodoList {
        "onDone"?: (event: CustomEvent<{ id: number, done: boolean }>) => void;
        "onRemove"?: (event: CustomEvent<number>) => void;
        "todos"?: Todo[];
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "app-todo-form": AppTodoForm;
        "app-todo-list": AppTodoList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-todo-form": LocalJSX.AppTodoForm & JSXBase.HTMLAttributes<HTMLAppTodoFormElement>;
            "app-todo-list": LocalJSX.AppTodoList & JSXBase.HTMLAttributes<HTMLAppTodoListElement>;
        }
    }
}
